export const BASE_URL = 'https://mydocsy.com';
export const PHONE_NUMBER = '+91 80690 61237';
export const WHATSAPP_NUMBER = '+91 78388 07404';
// export const WHATSAPP_LINK = 'https://wa.me/917838807404';
export const WHATSAPP_LINK = `https://wa.me/${WHATSAPP_NUMBER.replace(/\D/g, '')}`;
export const GOOGLE_FORM_ACTION_URL = 'https://docs.google.com/forms/d/e/1FAIpQLScAdQu56kMCUdU5oflF58MIg4x4jsRdKh0-m-E6Clqqvtnyyg/formResponse';
export const FIELD_NAME_ID = 'entry.1612902465';
export const FIELD_PHONE_ID = 'entry.321206955';
export const FIELD_CITY_ID = 'entry.560018661';
export const FIELD_DISEASE_ID = 'entry.1952828092';
export const YOUR_REFERRAL_CODE_FIELD_ID = 'entry.1477306052';
export const X_URL = "https://x.com/mydocsy/";
export const INSTA_URL = "https://www.instagram.com/mydocsy";
export const FB_URL = "https://www.facebook.com/mydocsy";
export const DEFAULT_PAGE_DESCRIPTION = "Docsy offers India's Most Advanced Surgical Care Experiences by pioneering minimally invasive, image guided pin-hole treatments using interventional radiology (IR). By partnering with only the best top interventional radiologists (average 20+ years experience) and premium IR centers with the latest equipment, Docsy provides safe, modern alternatives to traditional surgery - offering solutions which are Minimally Invasive and Maximally Effective."
export const BOT_URL = "https://docsy-chat.onrender.com" // TODO: Deprecate
export const AWS_BOT_URL = "https://chatbot.mydocsy.com"
export const GHOST_API_URL = 'https://blog.mydocsy.com';
export const GHOST_CONTENT_API_KEY = '177eac5ca351465fcc51bf089a';
export const CALLERID_APPRUNNER_URL = 'https://ibm4pjmrec.ap-south-1.awsapprunner.com/api/caller-info'